### ISSUE TITLE
Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Aborting

### ISSUE THREAD

**Issue by unixfox** [Gamocosm/Gamocosm#113]
I often get this error message a few minutes after clicking on "turn off":

>  2020 Feb 14 (01:51:03 PST)
> app/workers/wait_for_snapshotting_server_worker.rb:45:in `perform'
> Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Aborting
> 
> 2020 Feb 13 (17:22:32 PST)
> app/workers/wait_for_snapshotting_server_worker.rb:45:in `perform'
> Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Aborting

When this error occurs I've to click again on "turn off" because the server is still running but after that Gamocosm create a second snapshot and the previous one doesn't get destroyed. Then I need to manually remove the previous snapshot.

Is there some kind of timeout that needs to be tweaked because Gamocosm is unable to find the snapshot?

**Comment by DavidPD** [comment]
I've just started using Gamocosm and I'm seeing the same issue. I've tried shutting my server down 3 times in the last week and I've got this message once each time. Oddly enough, the second snapshot has worked each time for me so far.

I thought it was just unable to get the most recent id and was falling back the the previous snapshot, but I got this error once even after I left one of the previous "failed" snapshots alive. Now I've got 3 snapshots of the same server. the issue might be intermittent, but I haven't tested enough to be sure.

Also, by the way, thanks for making such a useful tool. It's a huge deal for me to be able to set this up so easily and without breaking the bank. Thank you!

**Comment by mbainter** [comment]
I recently started using it as well, and ran into this yesterday and again last night.  Last night I had everything locked down so I was able to see what was happening better.  I clicked turn off again and this time it properly shut down -- but it grabbed the wrong snapshot id.

last night it shut the instance down and successfully created snapshot id XXXX, but didn't update the target snapshot in gamocosm and left the instance in place.  This was in the server log:
``` 2020 Mar 31 (22:02:09 PDT) 
app/workers/wait_for_snapshotting_server_worker.rb:45:in `perform' 
Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Aborting

2020 Mar 31 (22:01:35 PDT)
app/workers/wait_for_snapshotting_server_worker.rb:32:in `perform'
Still waiting for Digital Ocean server to snapshot, tried 48 times ```

When I clicked turn off this morning, I got this:
``` 2020 Apr 1 (10:37:30 PDT)
app/workers/wait_for_snapshotting_server_worker.rb:32:in `perform'
Still waiting for Digital Ocean server to snapshot, tried 48 times
```
[snip]
```
2020 Apr 1 (10:31:43 PDT)
app/models/server.rb:202:in `stop'
Error stopping Minecraft server process Server not running, still proceeding with server shutdown ```

It successfully created the snapshot with id YYYYY and destroyed the droplet, but the target snapshot id is the snapshot id created last night (XXXX).

**Comment by Raekye** [comment]
So looking at the code, I can only think of 1 error.
So the [`wait_for_snapshotting_server_worker.rb`](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/wait_for_snapshotting_server_worker.rb) basically polls the snapshotting action/event and waits for it to finish.
It then expects there to be a snapshot id.
However, I believe there may have been a race condition where Gamocosm fetches the server information from Digital Ocean on [line 14 of `wait_for_snapshotting_server_worker.rb`](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/wait_for_snapshotting_server_worker.rb#L14), and the server isn't done snapshotting yet, but then by the time it fetches the action/event information on [line 29](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/wait_for_snapshotting_server_worker.rb#L29) it is done.
Then on [line 44](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/wait_for_snapshotting_server_worker.rb#L44) it thinks the snapshot is done, but it's still using the old information, which doesn't have the recently completed snapshot.
Since it thinks the snapshot is done but can't get the latest snapshot id, it aborts.
This seems kinda unlikely to be happening this often, although perhaps there are delays on when Digital Ocean updates this information.
Anyways, I've changed it to keep polling until it successfully gets/refreshes the snapshot id, or it completely times out.

The timeout is `1024 * 4 seconds`, or a bit over an hour.
If your servers are that big, or Digital Ocean has a hiccup, it may take that long...
though I've never seen it be an issue in my own use.
If you observe Digital Ocean itself taking an hour+ to snapshot, please let me know and I'll bump the timeout (I don't want to blindly bump the timeout hoping it fixes it)

Thank you all for your patience.
I've been a pretty bad maintainer for the past many years, and unfortunately I can only offer apologies.
Besides personal stuff and procrastination, I put off checking these things, which then makes me more anxious the longer I wait to respond, which makes me further want to look away from it.
However, I've finally committed to making the first nontrivial update in a while (when I first wrote Gamocosm I had to interface with Digital Ocean's API manually, but they now have an official ruby client which I've updated Gamocosm to use it), so hopefully it makes it easier for me to stay on this project after a long hiatus.
Surprisingly, usage of Gamocosm has been growing quite a bit in the last year (not entirely sure why as I don't advertise it).
Hopefully that + finally diving into things today gives me the motivation to stay on it.

Of course, I expect a lot of people have moved on after encountering these sort of issues with Gamocosm :P But I still appreciate you all who have tried it or even kept it, and reporting issues.

Anyways, we'll see how the future goes...

**Comment by mbainter** [comment]
Nah, don't sweat it.  This is incredibly useful and I'm glad you made it, and I know how frequently personal projects have to take a back-seat to life.  Now more than ever.

I'm definitely still using it, and I'm guessing other people are as well.  And, if you're interested in being active I may pitch in some PRs, as there are a few features I think would be nice to have.  For example, having a consistent smaller volume that's attached to droplets and used for backups - so if something happens to your snapshots you still have your backups.  I've also started some work supporting using restic to backup minecraft data to a secondary location which with some work could be potentially incorporated as an option.

**Comment by mbainter** [comment]
Okay.  I started up my server, ran it for a bit, then shut it down.  I had some communication issues at first (#117) but once I was able to reliably communicate and hit turn off it successfully shut down the node, made a snapshot and set the right snapshot on the advanced page.  It's just one data point obviously, but here lately it's been happening to me every time so it's an encouraging sign that you may have fixed this one with these changes.

**Comment by Raekye** [comment]
Ok, just randomly turning on and off servers, I did encounter the new log which indicates that there was a delay between the snapshotting action/event and the snapshot id appearing under the droplet information from digital ocean's API. So, there was _a_ problem, which should be fixed - hopefully that was _the_ problem. Thanks for letting me know!

**Comment by mbainter** [comment]
It's been through a couple more stop/start cycles and had no issues.  Looking good to me.

**Comment by mbainter** [comment]
Had this happen last night:
``` 2020 Apr 3 (23:55:22 PDT)
app/workers/wait_for_snapshotting_server_worker.rb:50:in `perform'
Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 111 times)
```

It *did* get the snapshot, but obviously took a lot longer than usual (I've never seen it go past 40) and it still worked so I think the bug is addressed.

One thing that might be nice to add to this log though is confirmation when it *does* get the snapshot that the process was completed successfully.

**Comment by Raekye** [comment]
Hmmm, it's a little concerning to me that it seems there's such a huge delay in the snapshot showing up in Digital Ocean's API, but I guess if it works in the end, it works. Gonna leave this open for a while before I close it

**Comment by Raekye** [comment]
Seeing as no-one has reported issues for 20 days, I'll close this for now. If anyone experiences this again, feel free to open a new issue.
