### ISSUE TITLE
Server still in "Not running" state after starting it

### ISSUE THREAD

**Issue by unixfox** [Gamocosm/Gamocosm#119]
I'm getting a rare case where I asked for the server to start but it stayed in the "Not running" state after doing its startup progress and I have to click again on the start button to have it started.

Here are my logs:
```
 2020 Apr 8 (02:48:00 PDT)
app/models/minecraft/node.rb:45:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2020 Apr 8 (02:47:55 PDT)
app/models/minecraft/node.rb:45:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2020 Apr 8 (02:44:47 PDT)
app/workers/wait_for_starting_server_worker.rb:48:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 1 times)
```

My minecraft server is Paper 1.15.2 and the VPS is located in Amsterdam.

**Comment by Raekye** [comment]
Hmmm, I'm pretty sure the fix is simple - it's probably a race condition where the minecraft server wrapper hasn't started yet, and I just need to make `StartMinecraftWorker` retry a few times. However, I'm confused that there doesn't seem to be a `Error starting Minecraft on server: ...` log from [line 22 of `start_minecraft_worker.rb`](https://github.com/Gamocosm/Gamocosm/blob/393ec7601ca3b3920c3e775e45e75b2536ca0d76/app/workers/start_minecraft_worker.rb#L22). I'll need to keep looking into this

**Comment by unixfox** [comment]
Thank you for your reply. I'll keep your updated if I get more logs once I encounter again the "Not running" state after starting the server.

**Comment by Raekye** [comment]
To be clear I haven't actually made any (relevant) changes yet xD Because based on the logs something unexpected is happening. I'm still (actively) looking into it

**Comment by Raekye** [comment]
Just an update, sifting through the code the past few days, I can't for the life of me figure out how that combination of logs and events could happen (as in, `start_minecraft_worker.rb` doesn't log an error, but Minecraft doesn't start). I did do some nontrivial updates to the minecraft server wrapper (which hopefully didn't break existing servers), but I don't think that should make a difference here

Please keep me updated if you keep seeing this issue

**Comment by unixfox** [comment]
I'm going to close this issue because I am unable to replicate the bug again.
If I get it again then I'll reopen it :).
