### ISSUE TITLE
Startup/shutdown times

### ISSUE THREAD

**Issue by mbainter** [Gamocosm/Gamocosm#124]
Digital ocean's performance gets pretty ridiculously bad on startup/shutdown with larger images.  I don't know if they're copying those to a USB and actually walking them down the datacenter to the VM host or what, but they can take forever for some reason.

So, a suggestion without having done any real research on how readily feasible it is with the framework you've developed:

Could an option be implemented to allow using a Volume for storing the minecraft data?  That way, the base image used to launch the instance could stay small (8GB/etc), which would also offer more flexibility for which instance type you run.  Then, after the system boots, the volume could be attached and mounted in /home/mcuser/.

This will mean additional costs even when not running, so I think it should be optional -- but it would be worth the tradeoff in time savings for some of us.

**Comment by Raekye** [comment]
Hi, ok, that is pretty interesting. Taking a quick read on their docs, it certainly seems feasible, although I want to make sure this is the best solution to the problem. Do you know exactly how big your current world is/next time you run your server, could you check? The command in SSH would be `du -sh /home/mcuser/minecraft`

One concern is, suppose you need 20-50 GB for your volumes. Pricing is $0.10/GB, so that's already $2-5 a month. Checking the pricing of a few standard Minecraft hosting services, $5 (sometimes less) is already the price of their cheapest plan, and at least 2 of them have no limits on storage. So I'm not sure how much you're actually saving by using Gamocosm. To be fair, you can still probably save a lot if you're using larger server sizes (CPU/ram)

A related thing I've considered in the past was a feature using Digital Ocean's [spaces/object storage](https://www.digitalocean.com/docs/spaces/) to back up worlds. See [this closed issue](https://github.com/Gamocosm/Gamocosm/issues/80). I didn't pursue it because it requires a $5/month base subscription, which I think most users of Gamocosm would not want?

But with this, I'm considering the possibility of Gamocosm subscribing to Digital Ocean's object storage, and all users' worlds would be uploaded to this central account, rather than every individual user needing an object storage subscription (I don't think this raises any security/privacy issues considering Gamocosm already has/requires API keys).

Although the base subscription includes 250 GB, and costs $0.02/additional GB, which is not very expensive, this could add up quickly, especially with inactive users. On one hand, I could add this as a paid feature for Gamocosm at cost ($0.02/GB, which I think is still really cheap), on the other hand, I would really like to keep Gamocosm completely free (I also do not want to deal with billing)

Anyways, I'll start looking into their block storage volumes.

---
By the way, have you seen additional problems with autoshutdown?

**Comment by mbainter** [comment]
I will check it out.  I think we are currently using only a few GB for the muser path, but the full image for the snapshot is ~35GB (OS+gamocosm+minecraft).  To store the minecraft bits should only be less than $1 a month.  Because of the modpack we're running we run a pretty large instance that would normally be $40/mo -- so that's still a significant savings.

I also looked at object storage, just for doing backups - but I agree that's not a great solution. I actually use a custom script I put together to do hourly snapshots locally and then use rclone to copy an appropriately pruned version of those snapshots to backblaze daily.  So far, with that setup I still fall in backblazes free tier so it's a better option than spaces.

I agree that a central purchase of storage would fix that -- but it introduces a pretty thorny situation for you.  Not only does it bring billing into the mix, it also puts you on the hook for all the data that gets stored in your spaces account, find a way to secure it between users, and to ensure that unscrupulous people aren't storing "non-minecraft" data in that path -- especially things that could get you in legal trouble.

My hope with this suggestion was that it would continue to keep the responsibility on the user to manage their volumes/storage.  It would also make it a lot easier to recover if something goes wrong with the snapshots.  

If it works out, you might even be able to do away with the snapshot process entirely and just use a "custom image" instead to launch from.  Or, at the very least, it would be easier for users to just start over with a fresh build if they move between tiers that have different storage size requirements.

We had to disable auto-shutdown for a bit because of usage patterns and this long-delay problem.  People would all log out for a short bit, and it would take way too long for the snapshot/startup process to complete -- so we've had to switch to manually shutting it down.  

However, when I am running it, it appears to work fine, and the shutdown processes have completed from the Gamocosm side just fine.  It's just DigitalOcean's side of the process that is agonizingly slow.

**Comment by Raekye** [comment]
Thanks for your response. I hadn't even thought of "unscrupulous" data; while Gamocosm is relatively under the radar, it's still something best not to have to worry about.

My concern with what you've said is that if the Minecraft bits are less than $1 a month (i.e. < 10 GB if I did my math right), how is the OS + Gamocosm taking 35 GB? Gamocosm only adds a few python scripts and libraries to wrap the Minecraft server with an HTTP API, and it only really installs some basic/necessary packages on the system. Perhaps the actual usage of the Minecraft world is small, but it causes the volume to be large due to internal fragmentation? I have no idea. But it seems that there's something going on that we don't know about, which could be a problem

Anyways, I actually just finished implementing support for volumes. I hope it works anyways :sweat_smile: I've tested it locally but not extensively. But fundamentally it's pretty simple so I hope it just works.

There is some awkwardness in how Digital Ocean sometimes automatically mounts volumes, and sometimes doesn't, but it should just work in the common case. If a server has an attached volume on Gamocosm, Gamocosm will create a `minecraft` folder in the volume, and create a symlink from `/home/mcuser/minecraft` to the Minecraft folder in the volume, instead of creating a regular folder. It's possible to attach a volume to an existing server, or detach and reattach volumes from servers, but you'll need to fix up a few things manually over SSH and it should just be much easier to create a new server with a volume and migrate Minecraft. Unfortunately, I don't think there's a robust way to automatically migrate an existing server to a server with a volume, so that will have to be done manually

I hate to ask users to test it, since it can be quite inconvenient if you're trying to play and it's not working, so I'll do more testing on my own, but if you want to try it out:

1. Download your server files from your current server
1. Create a new server
1. Go to the new "Volumes" tab in the navigation bar
1. Create a volume (ensure to select the same region as your droplet), and select your new server to attach it to
1. Start the new server. This will create the volume and set up the droplet to work with it
1. Stop Minecraft on the new server
1. Upload your server files

---
So here's a weird thing. Via the API, creating a volume, snapshotting a volume, and recreating a volume from a snapshot, are all instantaneous. This is weird because:

1. You wouldn't think these operations to be fast
1. How can snapshotting and recreating a volume be instant when snapshotting and recreating a droplet takes a long time?

So I'm not sure if I'm missing something, but as far as I can tell it seems to just work. Whereas creating and snapshotting droplets via Digital Ocean's API return events/actions which have to be polled for completion, creating and snapshotting volumes straight up returns the new resource.

So I've added another feature: you can "suspend" a volume by having Gamocosm snapshot the volume, and destroy the volume. Digital Ocean charges only $0.05/GB for a snapshot, versus $0.10/GB for an active volume. This is useful if you know you won't be playing for a while. Gamocosm should also automatically recreate the volume when you start the server, so you don't have to manually reload it

**Comment by mbainter** [comment]
The minecraft *world* is only ~4GB, but as noted I have a fairly thorough backup history:

- primary backup path, with a few days worth of hourly snapshot history, plus weekly/monthly/etc snapshots
- This is rcloned to another (secondary) path every day, and then pruned down to only emergency backup history (a scaled down GFS list) which is then rcloned to the remote storage

The primary backup path runs about 6GB, and the secondary copy for the remote backup is ~5GB.  I actually had a bug in my setup that was causing the primary not to get pruned, so that had grown to around 45GB, and that's presumably why it was taking so long.

Regardless - I've moved all of that to a volume that gets attached on startup now with your new feature and that appears to have resolved the problem for me.

**Comment by Raekye** [comment]
I see, thanks for clarifying, that is a nice backup setup! I noticed a bug with the `setup_server_worker.rb` causing it to create an additional symbolic link and then fail the next time. Saw a failed job which I assume was related to your volume/server. It should be fixed, based on my own tests

The problem was with the SSHKit library, if the command is given as a string, which it was on [line 237](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/setup_server_worker.rb#L237), it executes the command without any context (i.e. ignoring the `within` block on line 222), so it wasn't checking if the correct file exists. Was pretty lucky (to find this bug so quickly) since I was recently reading over SSHKit's docs and remembered that gotcha... don't know how long it would have taken if I didn't know that

**Comment by mbainter** [comment]
We've started/stopped multiple times over the last week and it has performed much better.  Both having less to restore and being able to just mount the volume has helped tremendously.
