### ISSUE TITLE
How to increase the Minecraft server RAM allocation with Gamocosm?

### ISSUE THREAD

**Issue by ZQuinones** [Gamocosm/Gamocosm#134]
I tried `java -Xmx2G -Xms2G -jar minecraft_server-run.jar nogui`
but I got an error`Error: Unable to access jarfile minecraft_server-run.jar
`

**Comment by memtech3** [comment]
Did you make sure that minecraft_server-run.jar is the name of your server jar file? If I remember correctly, the default name on gamocosm is server.jar

**Comment by Raekye** [comment]
For future reference, one can start Minecraft with a custom command (such as specifying custom Java flags such as `-Xmx` and `-Xms` for RAM) by creating a `minecraft_server-run.sh` script. This requires you to use [SSH](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH) or the new [web console](https://github.com/Gamocosm/Gamocosm/wiki/Web-Console). Ensure to make it executable: `chmod u+x minecraft_server-run.sh`.

Note that Gamocosm should already start servers with the same memory as your Digital Ocean droplet. Technically, you could use more memory because of swap, but that would likely greatly slow down your server; if anything, you more likely want to slightly _decrease_ the amount of memory for the minecraft server to increase performance (to avoid swapping).

For sanity, you can check the flags Minecraft was started by listing all processes and search for it: `ps aux | grep minecraft`.

The `minecraft_server-run.sh` script is documented under the [Installing different version of Minecraft](https://github.com/Gamocosm/Gamocosm/wiki/Installing-different-versions-of-Minecraft) wiki page (yes, I realize now it should probably be documented somewhere more general as well).
