### ISSUE TITLE
Gamocosm latest server not working after the update of 1.17....tried making multiple servers but they just wont run....getting the error - (Unable to start Minecraft: MCSW API error: HTTP response code 500, {"status"=>"badness"}. Please contact the server admin about this) _

### ISSUE THREAD

**Issue by bitansaha13** [Gamocosm/Gamocosm#150]
Gamocosm not working after the update of 1.17....tried making multiple servers but they just wont run....getting the error - (Unable to start Minecraft: MCSW API error: HTTP response code 500, {"status"=>"badness"}. Please contact the server admin about this)
_...I think its due to the server software being outdated in gamocosm site....ever since the caves and cliffs updates latest server wont run

**Comment by Brottweiler** [comment]
1.17 requires Java 16, and the java version that gamocosm installs is java 8.

**Comment by Brottweiler** [comment]
Ok, here's a manual workaround for this.

Install OpenJDK 16
```bash
sudo dnf install java-latest-openjdk.x86_64
```

Then change to use java 16 by default:
```bash
sudo alternatives --config java
```
Press `2` then `Enter`. You probably need to restart the entire box because Gamocosm might error out because it had crashed.

**Comment by Raekye** [comment]
Hi, thanks @Brottweiler for the fix. Gamocosm should install Java 16 by itself now, although I haven't automatically updated the default Java version because older Minecraft versions possibly won't run on Java 16 (certainly if you go back far enough I recall Minecraft did not run on Java 9+, but I'm not sure if they started supporting Java 16 before 1.17). You'll have to [SSH](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH) into the server and run the second command @Brottweiler mentioned

**Comment by Brottweiler** [comment]
I'd also like to point out how to upgrade to Java 16 if you are running an older Fedora version. I have another server from 2020, that was running **Fedora 31**. The latest Java version available was 15.

Here is the page with information about upgrading https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/

Since I was running Fedora 31, that page says it's recommended to upgrade to `33` (only skipping one version). I did that, and after that I upgraded to `34` for the sake of it. You can look at the [version history](https://en.wikipedia.org/wiki/Fedora_version_history#Version_history) on Wikipedia.

You could either install `java-latest-openjdk-headless.x86_64` before or after upgrading Fedora, doesn't matter. 

When you upgrade, the last command you run is `sudo dnf system-upgrade reboot`. This will "reboot your machine into the upgrade process running in a console terminal". You won't be able to SSH, but you can open the **Console** from the DigitalOcean dashboard to check the progress, it takes a few minutes and you will see console output until you get a login window.

Now I am successfully on Fedora 34, using Java 16, on that server. So if you have an old server that doesn't have Java 16 available, you gotta upgrade your Fedora version first.

**Comment by Raekye** [comment]
Ok 6 months later, this should be handled properly now. Specifically, internally the Minecraft versions in [`config/minecraft_flavours.yml`](https://github.com/Gamocosm/Gamocosm/blob/518ce44f302e3cc1078d65c403ff39ff01f93f2d/config/minecraft_flavours.yml) have been separated based on pre- and post-java 8, and the scripts in the [`gamocosm_minecraft_flavours`](https://github.com/Gamocosm/gamocosm-minecraft-flavours/tree/5d530559114b48f1c6634f91a1d0dc79203d82cf) repo have been updated to install the corresponding version of Java. To keep things simple, I also removed most of the miscellaneous minecraft versions as it's been ages since they've been officially tested, and it'd just be a trap for users

I manually (aka sketch-ily) tested a few versions and it should be good now :P Closing this issue for now, feel free to comment/open a new issue if I missed something

Thanks all for your patience
