### ISSUE TITLE
mcsw.service fails (Fedora 35)

### ISSUE THREAD

**Issue by Brottweiler** [Gamocosm/Gamocosm#161]
For Minecraft 1.18.1 I updated Fedora from 34→35, and after the [update process](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/) and final reboot, `mcsw.service` fails to start.

```
[systemd]
Failed Units: 1
  mcsw.service
[mcuser@ ~]$ systemctl status mcsw.service
× mcsw.service - Minecraft Server Wrapper
     Loaded: loaded (/etc/systemd/system/mcsw.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-12-14 17:53:09 UTC; 2s ago
    Process: 796 ExecStart=/usr/local/bin/run_mcsw.sh (code=exited, status=1/FAILURE)
   Main PID: 796 (code=exited, status=1/FAILURE)
        CPU: 38ms

Dec 14 17:53:09 .minecraft.gamocosm systemd[1]: mcsw.service: Scheduled restart job, restart counter is at 5.
Dec 14 17:53:09 .minecraft.gamocosm systemd[1]: Stopped Minecraft Server Wrapper.
Dec 14 17:53:09 .minecraft.gamocosm systemd[1]: mcsw.service: Start request repeated too quickly.
Dec 14 17:53:09 .minecraft.gamocosm systemd[1]: mcsw.service: Failed with result 'exit-code'.
Dec 14 17:53:09 .minecraft.gamocosm systemd[1]: Failed to start Minecraft Server Wrapper.
```

(censored the name of the server, that's why hostname is missing and stuff).

**Comment by Brottweiler** [comment]
I assume since python3 updated yesterday, something needs to be updated in the code.
```
[mcuser@moleville2 ~]$ flask 
Traceback (most recent call last):
  File "/home/mcuser/.local/bin/flask", line 5, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask'
```

**Comment by Brottweiler** [comment]
Progress after some troubleshooting:

`setup_server_worker.rb` [checks](https://github.com/Gamocosm/Gamocosm/blob/d6f9f70a65cf28c88cc7d571da52b981fc8491e4/app/workers/setup_server_worker.rb#L192) for if Flask is installed and if it's not it [installs it](https://github.com/Gamocosm/Gamocosm/blob/d6f9f70a65cf28c88cc7d571da52b981fc8491e4/app/workers/setup_server_worker.rb#L194).

Checking manually shows Flask not installed
```
$ pip3 freeze | grep Flask
$
```

Since Flask seems to not be installed, install it manually:
```
$ pip3 install --user flask
$ pip3 freeze | grep Flask
Flask==2.0.2
```

Now I rebooted the server to test if it worked, and the Minecraft server failed to start. I ran `sudo alternatives --config java` and saw that Java 8 was default, so I changed that to Java 17 (which is required by 1.18).

Starting server via gamocosm still fails, but I can start it manually when I SSH.

**Comment by Raekye** [comment]
Hi, thanks for the report and troubleshooting (and patience)! I can indeed reproduce with the following steps:

- Create new server with gamocosm (Fedora 34)
- `pip freeze` (as `mcuser`) includes Flask
- Run the [update process](https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/)
- Reboot with `sudo dnf system-upgrade reboot`
- `pip freeze` (as `mcuser`) nolonger includes Flask

After some investigating, as you suspected, it is due to Python being upgraded from 3.9 -> 3.10. Specifically, `pip install ...` places packages in `~/.local/lib/python<version>/site-packages`. So for Fedora 34 this is `~/.local/lib/python3.9/site-packages` and for Fedora 35 this is `~/.local/lib/python3.10/site-packages`, explaining why Flask "disappeared".

Also as you found, `setup_server_worker.rb` should try to (re)install Flask every time it runs. Note that it isn't used when you reboot at the command line or use the "Reboot" button on Gamocosm (that just does a power off-power on via the Digital Ocean API). Unless I remembered wrong from my testing, doing a full stop with Gamocosm (where it snapshots and destroys the server) and full start (which will run `setup_server_worker.rb`) did seem to work as expected for me (after the Gamocosm stop-start, `mcsw.service` should start correctly).

If you remember, if you did not do a Gamocosm stop-start, I believe this issue is solved. I will document this behaviour better in the wiki. If you did do a Gamocosm stop-start after the upgrade, and it still didn't (re)install Flask by itself, then I need to look further into this.

Thanks again for your patience!

**Comment by Brottweiler** [comment]
I never did a stop-start, so that seems to make sense!

**Comment by Raekye** [comment]
Ok great! I think this is solved then? Thanks again for reporting this, I am doing some cleanup and will add it to the wiki today

**Comment by Brottweiler** [comment]
Yep, fine by me. 🙂
