### ISSUE TITLE
Cannot access to SSH FTP 

### ISSUE THREAD

**Issue by AL-NGU** [Gamocosm/Gamocosm#181]
Hello!

I'm trying to access the SSH FTP to upload my world. It's showing me the issue below: it's telling me that my browser is too old. Could you please let me know how to fix this?

I've tried to create the new droplet, create new server. it doesnt work :/ 

Thanks in advance!

![2023-06-24 23_25_25-Window](https://github.com/Gamocosm/Gamocosm/assets/117751278/388ca315-a221-4a2b-bf51-255b9e46b20f)

**Comment by Raekye** [comment]
Hi, sorry for the (moderately) slow response. That web interface does give you access to a terminal/shell to run commands, but isn't SSH/FTP itself. If your goal is to upload files, you'll need to use an FTP client (specifically, SSH also gives you access to a terminal, and FTP can operate over SSH. You could upload files with SSH with something like `scp`, but an FTP client is probably easier. I don't think the web interface supports uploading files even if you could get in). [This wiki page](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH) has more information on using FTP

As for the error with the web interface, it's hard for me to say, since it's a separate piece of software ([Cockpit](https://cockpit-project.org/running)), but for starters, what browser (and version) are you using?

**Comment by AL-NGU** [comment]
Hey Raekye!

Thanks for the reply! I gone through the wiki page, and instructions are clear.

About the web interface though, here's the version
![image](https://github.com/Gamocosm/Gamocosm/assets/117751278/b742b596-f525-40c9-aa83-50faebfa0817)

**Comment by Raekye** [comment]
Hi - sorry again for the delay (it seemed like you were able to get going without the web interface, so I got lazy about looking into the web interface issues)

I searched for error reports with Cockpit - it seems to be [this issue](https://github.com/cockpit-project/cockpit/issues/17773), which is from last year but also the Fedora image being used by Gamocosm is about a year old.

I've updated the Fedora image to the latest version and tested on Firefox and Chrome (`Version 114.0.5735.198 (Official Build) unknown (64-bit)`) so hopefully newly created servers won't have this issue.

For an existing server, if you want to update the web interface, you'll have to access the shell through SSH first (which I understand may be a bit daunting/inconvenient - the point of exposing the web interface in the first place was to try to make accessing the shell more friendly). Once you're in the shell, you should just need to run `sudo dnf -y upgrade` (and reboot with `sudo reboot now` or through Gamocosm's control panel). If the wiki instructions for SSH aren't clear or if you have any other questions don't hesitate to ask!

**Comment by Raekye** [comment]
Closing this issue for now since I think it should be fixed - please don't hesitate to re-open (or make a new issue) if you're still experiencing problems. Thanks for your patience!
