### ISSUE TITLE
tmux - Installed but not utilized?

### ISSUE THREAD

**Issue by Lowsound** [Gamocosm/Gamocosm#28]
I was searching how to send commands directly to Minecraft on my Gamocosm server and came across a bunch of forum posts and blogs about using Screen to leave a session running specifically for the MC process, thus allowing you to return to it and use it. 

I then found the Send Command to Server feature that already exists with the Gamocosm control panel, and while thats useful in some ways, isn't in others(no stdin or out).

I then read that tmux comes installed on our Gamocosm droplets, but isn't actually used for anything.. 

Maybe this is completely unreasonable, but would it be possible to have Gamocosm launch Minecraft within tmux allowing a user to ssh in and switch to that tmux session?

How else can I setup scheduled backups of my Minecraft world(other than the Gamocosm control panel)?

Thanks,

L

**Comment by Raekye** [comment]
Hi Lowsound, I see you've connected in IRC several times but I've always missed you D:

That's a really good question! In fact it's the first thing I tried when making Gamocosm, and other users have asked before. As you said, it's a common way to run Minecraft servers, but right now tmux is only installed for users' use

If there was a killer reason I stopped scripting tmux, I don't remember it right now xD but there are still a few grey-area reasons. However, I'm open to discussion, and especially at this point in development (relatively bug free, I hope xD ), I'm open to trying new things

The choice between a wrapper and tmux came down to one "should always work" and the other "might not always work". And to understand we also have to look at the way the Minecraft server behaves

I'd guess the Minecraft server was originally written for people launching it with a GUI from their desktops, and it hasn't been changed since. So there's the assumption that *when a user wants to do something, they are directly interacting with it*. But servers in the traditional sense aren't interactive; they're typically long running, background processes that serve clients. Servers are typically non interactive

So screen and tmux are popular methods of running Minecraft servers because they're interactive; tmux is a *terminal* multiplexer - it can detach when you're going away, and re-attach so you can type stuff to and read stuff from the server process. But in the linux server world this is kinda hacky. Ideally, a server is non-interactive, and is a long running process in the background - a daemon

Tmux is great for interactive stuff, but it's not so great for automatic management. There's no direct way to get the Minecraft pid - you can `ps aux | grep java | grep minecraft_server-run.jar` or `tmux list-panes -t <minecraft session> -F '#{pane_pid}'` and parse but these won't necessarily work; it's hacky

There are a lot of (arguably extreme) edge cases that don't work trying to script tmux because it's not truly a good way to run server processes, and between something that should always work (wrapping and properly daemonizing the process) and something that might not always work, I ended up going the wrapper route

---
But yes, I know the lack of an interactive console sucks. However, I figured it shouldn't be a big problem

- After op-ing yourself, you can do most things from the minecraft client
- If you need to run a bunch of commands one time, you can stop the Minecraft server on Gamocosm, SSH, and start the server yourself

Of course, with user feedback I always have to reconsider. To script scheduled backups, I'm guessing you're using cron. Here's a theoretical solution

```
# get the second line (password) from the auth file
MCSW_PASSWORD=$(sed -n '2{p;q}' /opt/gamocosm/mcsw-auth.txt)
# exec a "save-all" through the server wrapper
curl -d '{ "command": "save-all" }' "http://gamocosm-mothership@$MCSW_PASSWORD:localhost:5000"
# zip up your world
cd "$HOME/minecraft"
tar -czf "backups/$(date).tar.gz" world
```

Let me know what you think. If this type of solution seems good to you, you might want to try the commands individually first, as I wrote them off the top of my head xD (if you're not so familiar let me know I can also test it myself and say "it should work")

One of the reasons I wrote a new wrapper is so it could be scriptable like that

---
In the end, I know lacking a web console or tmux console is inconvenient, but at the time I thought I made the right tradeoffs. Let me know what you think of the reasons and workarounds! I'm always trying to improve

**Comment by Lowsound** [comment]
Oh hey, wasn't expecting that much of a response!
Aw dude, I missed you too.

I totally understand the choice to go with the Wrapper instead of tmux. 
Thanks for dropping some knowledge Raekye.

I've been playing with your suggestion - Everything seems to work well except the curl line
```
curl -d '{ "command": "save-all" }' "http://gamocosm-mothership:$MCSW_PASSWORD@localhost:5000"
```
For me it spews out:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

I even swapped out gamocosm-mothership with my own hostname and IP to no avail :( 

What am I missing?

**Comment by Raekye** [comment]
Ah very sorry stupid on my end D: needs a "/exec" at the end of the url (`curl -d '{ "command": "save-all" }' "http://gamocosm-mothership:$MCSW_PASSWORD@localhost:5000/exec"`)
