### ISSUE TITLE
Enable zram (upgrade to Fedora 22)

### ISSUE THREAD

**Issue by vemacs** [Gamocosm/Gamocosm#36]
Will help for instances with low-memory and perform far better than swap. It's built in Fedora 22, so it would be cool if you could upgrade instances to Fedora 22 and run `sudo systemctl start zram`.

**Comment by Raekye** [comment]
That's pretty cool, never heard of it. From what I've read here http://askubuntu.com/questions/471912/zram-vs-zswap-vs-zcache-ultimate-guide-when-to-use-which-one and http://stackoverflow.com/questions/18437205/difference-between-zram-and-zswap it seems zram is for when there's no swap (physical or file), and zswap should be used when there is.

I think the smallest servers (512MB) are a bit small even with compressed ram, so I'd be careful of completely removing swap. Any thoughts between the two - zram and zswap? It seems zswap can also compress pages in ram, but doesn't look like it's using zram, but a separate project

**Comment by vemacs** [comment]
zram is the preferred implementation in modern *nixes. There is no reason to fully remove swap.

**Comment by Raekye** [comment]
The askubuntu link says "if other swap devices (HDD/SSD) are present they won't be used optimally", and that you could suffer from LRU inversion - if it fills up pages start going to the disk/swapfile, instead of replacing the pages in ram. Do you know of any way to mitigate or deal with this?

I'll remove the minimum heap size flag. In hindsight it should be pretty useless unless you straight up have tons of RAM. Thanks for pointing it out!

**Comment by vemacs** [comment]
I've never heard of that issue before and have never experienced it. When I am low-RAM on VPSes, I run swapon -s and see absolutely nothing swapped to disk, and I haven't seen the claim in that AskUbuntu answer substantiated anywhere else. From my own experience (and benchmarks from places like Phoronix), zram is a drop-in free performance improvement for people who are willing to sacrifice a bit of CPU power for more responsiveness under low-memory scenarios.

**Comment by Raekye** [comment]
I removed the minimum heap size flag, it should be unnecessary

As for zram, I also saw an askfedora thread saying it is included in fedora 22, but it doesn't seem to exist on the digital ocean droplets I'm creating. Don't find any zram packages in the repository either. Have you got zram working on a DO fedora server?

**Comment by vemacs** [comment]
I don't personally use Fedora, but the second answer on askfedora mentions kmod-staging in the rpmfusion repo.

**Comment by Raekye** [comment]
Alright, I was hoping it'd be available without adding repositories/packages since it seems it's supposed to be in the kernel and fedora 22 already, just wanted to check I wasn't missing something. I'll be really busy this next week but should get this through next weekend

**Comment by Raekye** [comment]
I added zram support. I set it to be 128M (there's a 1GB swapfile). I never found any included systemd service files, but found that the kernel mod was already installed/available. Just wrote a minimal service file for starting zram as you can see in `seutp_server_worker.rb`. Did some basic testing to make sure it's working

Technically there should be serious testing before performance tuning, but this is largely a dev project (rather than a "product" project) so we do it because it's cool :P Thanks for showing me this!

Sources:
- http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/blockdev/zram.txt
- https://wiki.archlinux.org/index.php/Maximizing_performance#Zram_or_zswap
- https://wiki.archlinux.org/index.php/Systemd_FAQ#How_can_I_make_a_script_start_during_the_boot_process.3F

**Comment by vemacs** [comment]
Most distros set it to half the size of physical memory. Mind setting your script to do that? It'll still swap to disk when needed.

**Comment by Raekye** [comment]
This has been added in the [latest commit](https://github.com/Gamocosm/Gamocosm/commit/f95837e9d2ba2119486a40be341cb77401991acd), as well as the wiki updated

The script is based off the ubuntu `zram-config` package. In addition to using half the RAM as the zram size, it creates as many devices as there are CPUs
