### ISSUE TITLE
Use Server List Ping for auto-shutdown instead of query

### ISSUE THREAD

**Issue by vemacs** [Gamocosm/Gamocosm#37]
Query is not enabled by default, and may not be supported by alternate server implementations. Why not use the standard 1.7+ server list ping first, and then fallback to query?

Ruby: https://github.com/blockgiven/takumi-server_list_ping
Python: https://github.com/Dinnerbone/mcstatus

**Comment by Raekye** [comment]
At the time of writing 1.7 and the 1.7 server list ping were new, and it was fragile supporting old ping protocols (server doesn't respond if you don't follow its protocol, so you set a timeout, then try another protocol version). The query protocol seemed nice because it has remained unchanged

It's been over a year and probably most servers are on 1.7+ now, so I'll look into supporting that. Should be straightforward but probably low priority as I want to focus on scheduling asap

**Comment by Raekye** [comment]
Well, 4.5 years later I'm pretty sure most people are running servers >= 1.7, so I've gone ahead and added that. Gamocosm will first try the [server list ping protocol](https://wiki.vg/Server_List_Ping), then fall back to the old query protocol. This means `enable-query=true` probably isn't necessary anymore, although I'm maybe it's better to still make it enabled by default (when setting up new servers)
