### ISSUE TITLE
Cuberite startup script looks for wrong binary

### ISSUE THREAD

**Issue by DanielBaird** [Gamocosm/Gamocosm#38]
I just made an account and set up a fresh Cuberite server, and the server came up but not the minecraft server.  The startup script was looking for ./MCServer but there was no file called that -- I edited the startup script to run ./Cuberite instead.

Then the website's "start" button worked.

**Comment by Raekye** [comment]
Ah thanks, after they changed their name to Cuberite the executable compiled was still `MCServer`. I kept an eye on it but after a while got lazy and only checked the `easyinstall.sh` in their repository to see if it had been updated (seems like it hasn't?)

This should be fixed in the [gamocosm-minecraft-flavours](https://github.com/Gamocosm/gamocosm-minecraft-flavours/commit/83aeb3670da6e1cb15b808323b2974b2de073015) repo

Thanks again!
