### ISSUE TITLE
SSH Error?

### ISSUE THREAD

**Issue by Ajusa** [Gamocosm/Gamocosm#39]
When I go to turn on my server, the log spits out errors for ssh and the Server takes 5 minutes to start. I have changed the default password. How to I stop the errors?

**Comment by Ajusa** [comment]
Also, I haven't been spaming the start and stop

**Comment by Raekye** [comment]
Was this saturday? If so I was moving the database server and did something stupid so there was some downtime... is it still a problem now?

Can you provide more details? When you say "5 minutes to start", do you mean eventually it starts and works, or it doesn't at all?

If it does start after a while and a bunch of messages saying it couldn't connect, that's probably something wonky on digital ocean's side. Let me know if it persists

**Comment by Ajusa** [comment]
This was Saturday. The droplet was started, but it was 5 minutes before
Minecraft was running on the Server. I'll provide more info later, if this
problem persists.

**Comment by Ajusa** [comment]
It still persists...
Here is a log
2015 Dec 12 (10:03:30 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:03:27 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:03:24 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:02:14 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:02:11 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:50 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:47 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:17 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: execution expired
2015 Dec 12 (10:01:13 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2015 Dec 11 (17:13:35 PST) app/workers/wait_for_stopping_server_worker.rb:31:in `perform'
Digital Ocean took too long to stop server. Aborting
2015 Dec 11 (17:13:19 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 31 times
2015 Dec 11 (17:13:07 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 30 times
2015 Dec 11 (17:12:48 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 29 times
2015 Dec 11 (17:12:39 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 28 times
2015 Dec 11 (17:12:31 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 27 times
2015 Dec 11 (17:12:15 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 26 times
2015 Dec 11 (17:11:54 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 25 times
2015 Dec 11 (17:11:41 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 24 times
2015 Dec 11 (17:11:33 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 23 times
2015 Dec 11 (17:11:18 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 22 times
2015 Dec 11 (17:11:11 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 21 times
2015 Dec 11 (17:11:02 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 20 times
2015 Dec 11 (17:10:51 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 19 times
2015 Dec 11 (17:10:37 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 18 times
2015 Dec 11 (17:10:28 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 17 times
2015 Dec 11 (17:10:17 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 16 times
2015 Dec 11 (15:50:41 PST) app/workers/setup_server_worker.rb:77:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 0, Exception while executing as root@104.131.69.18: Connection refused - connect(2) for 104.131.69.18:4022). Trying again in 16 seconds

**Comment by Raekye** [comment]
I've gotten these errors before, though of course I can't be sure it's the same cause. As far as I'm aware, these are all glitches in DO's system. I don't find them common/too troublesome, but they include:
- droplet not having connectivity after started (what I listed above - shows up more common if recently created/destroyed droplets, but sometimes even if you're not doing that)
- certain events hanging (e.g. stopping a server)
- event says it's completed but never actually occurred or succeeded (e.g. stopping a server "done" but server status is "active")

I also noticed if you check status.digitalocean.com they were having issues on December 11th as well as today

---
If this occurs again, could you quickly try to SSH into the server? If you can't (which seems to be always the case for me), then I'm pretty sure there's nothing gamocosm can do (in terms of our code), which I suppose is a downside of this whole system/setup (depending on DO's reliability) :/ If you can get in... I'll have to think, but that still isn't necessarily fixable on our side (since DO's internal network could still be wonky - gamocosm runs on a DO server)

I'm pretty sure it's a connectivity issue because you can also see it can't connect via HTTP (MCSW API) - a different protocol. MCSW starts automatically so even if the setup server worker fails for an already-created server, contacting the MCSW should still work. It's still running on your created server, but just it's network connectivity is borked. So like 5 minutes later when it finally comes up, you see it "working", even though it's started the whole time. That's my guess anyways

If you can't SSH into the server when you get those errors, and it's happening often, let me know, and I'll try to contact DO. All these issues have definitely irked me (been +1 years of running), but I only ever find these errors after the fact; I've never been able to reproduce them or have any specific details. The same way I can't do much about gamocosm errors without a lot of details, I know the DO guys can't do much if I just say "I sometimes get these vague issues"

I'll review my side again, and see if I can gather up some stuff to send to DO

**Comment by Ajusa** [comment]
Okay, thanks. I seem to have bad luck with these errors, as they always crop up when gamocosm is being updated or DO is having issues. Thanks for looking into this, I will see if it persists and whether I can reproduce it.
