### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by Ajusa** [Gamocosm/Gamocosm#41]
Just a suggestion here. If other people want it, I think it would be nifty to implement themes with some javascript and Ruby. I don't know about the Ruby part (to save the setting?) but I can do this in javascript.
Basically, all of the actual css would be from the open source team at www.bootswatch.com
All that would need to be done is to switch the styles. Here is a "teaser". (I don't have it implemented quite yet :P)
![capture](https://cloud.githubusercontent.com/assets/7073362/11516606/441d3f9c-9852-11e5-9e7e-6ada8e985105.PNG)

**Comment by Raekye** [comment]
As you know gamocosm uses bootstrap, and bootstrap looked great when it was new, but now it's everywhere and just looks like another shitty "web 2.0" "app" xD Unfortunately I have no graphical ability (I've tried multiple times), so that's all there is

I've looked into bootstrap themes but haven't bothered with them because like bootstrap, they're pretty much all generic "web 2.0" stuff. I'm not sure how to really describe it... but despite looking new I don't find they actually look much better

I've sorta been looking for a designer (I've even considered paying a freelance, but for a project I work on purely for utility, not personal gain, it's hard to justify a non-small fee unless I'm pretty sure I'll like it), and sorta hoping one day someone who's good at design could make something minimally unique and hopefully specific to minecraft (just something simple like an icon or texture or colours) :P

Like check out forge, spongepowered, terrafirmacraft, bukkit, spigot, etc.. They're mostly forums, so there's not even that much variety, but I recognize them when I see them

Regardless, if you think there's a nice theme I'd be happy to see it or check it out myself, but I wanted to voice my concerns. Of course, if I'm not a fan of something but multiple other people are, there's a good chance I'll go with it

**Comment by Ajusa** [comment]
How about someone writing a newly designed site? Would you go with that? I can try at that. What do you mean by something simple like and icon or colors?

**Comment by Raekye** [comment]
I would definitely be ok with someone designing a new site :) that was sorta the end goal anyways, but I want to warn it can take a deceptively long time (I'm assuming you mean redo the whole UI, like changing a lot of the HTML instead of mostly adding CSS). I'd be happy to help with all the quirks along the way, but here are some things to consider:

- the raw code is non-small, and us developers are known to always underestimate how long code actually takes to write :P web design, though not programmatically challenging still takes a long time, even for professionals
- if you're just moving things around on the same pages, this won't be an issue, but if you start changing the "bigger" layout of the pages, you also got to start changing the controllers
    - sometimes there are subtle things such as positioning (takes a while to tweak and get it right), how it interacts with the demo page (which is dynamically generated), and how it uses the "remote" objects (caching Digital Ocean API requests, making as few requests as possible per page load)
- I think I'm a very open maintainer; I'll discuss and explain code and listen to others' feedback, but that doesn't mean I'll accept everything
- Though it looks bad, the code is clean and easy to maintain. Maybe I think something looks better, but if it adds a lot more code it might not be so good. That being said, this problem should mostly be fixable

If you do want to try designing a new site, I'd recommend doing a mockup of the main page first (either with static HTML or photoshop). You should be ready for a lot of changes and hours sunk in to reach completion. Again, I'll do my best to help along the way :)

---
Without redesigning the site, I *think* just few "basic" CSS changes could go a long way. It won't be as nice as a full overhaul, but I think it could make gamocosm look a lot nicer

Right now, gamocosm is black and white, with green and blue buttons. Now obviously these are just my own impressions, maybe I'll make no sense xD The black and white (and grey) are drab obviously. The two shades of green are too... primary? Bright? If you look at [terrafirmacraft][1] or [forge][2], their green and blue respectively are a lot... warmer? Deeper? I myself tried to pick some warmer colours... without success xD The blue I picked for "stop" buttons was the result of that, but as my friend laughing-and-crying-ly pointed out, stop buttons aren't blue xD

Now look at some minecraft hosting sites (these things apply to both redesigning the site or just trying to make CSS changes): [nodecraft][3], [mc pro hosting][4], and [realms][5]. They both look a lot... "fuller" compared to the greyscale gamocosm. Let's see, what do they have? Nodecraft has a textured banner, then an image banner, then black, then some sort of minecraft stone texture background, and a very warm footer with inset bars for texture. MC pro hosting is mostly dark (not really a fan of that, but it can be made nice like they have done). It also has textured backgrounds - the map and the textures behind all their feature points. Realms is the most simple but still has a carousel/big images, and a very warm background colour. And of course, they all have logos they all integrate into the rest of the site - e.g. the green red blue yellow of nodecraft is also used for highlighting nav bar buttons, the green of mc pro hosting is the green used for other text. I'm not expecting a logo, but I wanted to show an example of consistency and "identity" when designing the UI/picking a theme. Right now Gamocosm uses a generic free font. I'm not sure what people think of the font. But picking someone else' generic bootstrap theme your guaranteed a generic font and theme (non-identity)

Hopefully that gives you a better idea of what I was thinking of, and if you want to go forward all the "warnings" before you start. I don't mean to scare you; I'll definitely try to be as helpful as I can xD But I don't know what's your background in coding or design and it 's better you (or anyone else in the future looking at this) knows what might be coming

Let me know if you have other thoughts/questions!

[1]: http://terrafirmacraft.com/index.html
[2]: http://www.minecraftforge.net
[3]: https://nodecraft.com
[4]: https://mcprohosting.com
[5]: https://minecraft.net/realms

**Comment by Ajusa** [comment]
Mind overloaded... My background in coding is reletivley small; The hardest thing I have other done was make an Ionic AngularJS app and write the backend in Go. The issue I currently have is experience. I am still in high school, so finding time is an issue. For now, I will redesign the front page and other pages, but leave the administrative panel mostly alone. The actual UI redesign is a bit over my head, because I don't know "good" design when placing menus and stuff. I will make a github repo on my account, so if anyone else reading this wants to contribute, they can submit a pull request.

**Comment by Ajusa** [comment]
So basically, this is what you are trying to describe, that you don't want:
http://tiffzhang.com/startup/

**Comment by Raekye** [comment]
No worries, everyone has to start somewhere for everything :P And I totally understand real life constantly gets in the way even when you think you got a window xD I don't expect you to work X hours on it or finish by Y date. Unlike adding features or fixing bugs, there's no 1-dimensional start -> finish, and as an "art" it's subjective, which makes it more challenging/time-consuming. Even if you never finish this, I'm happy for your interest and hopefully that you enjoyed working on it ^^ 

**Working on this should be something you enjoy.** Above all, I just don't want to waste your time by miscommunicated goals. In case for any reason I'm not comfortable merging (I'm sure you'll do a better job than me :P but need to consider complexity, consistency, etc.), hopefully you still got a lot out of it (learning, fun of coding)

---
Again, maybe I'm making it sound discouraging xD In reality I think it will go well, but better make it sound worse so it's better than the other way around. I'll do my best to help with whatever I can, so just post again here (or message me on reddit or IRC) if you have any questions or want feedback!

---
For the site you linked, I think a full page image banner is nice, though it doesn't work for everything. I tried a few images of my own for gamocosm but they didn't blend. I'm actually not sure I've seen any big minecraft sites use it, my guess because minecraft scenes tend to have a lot of detail, which doesn't blend well as a background (not saying don't try!)

Since it's auto generated I get that it won't be as polished, but yeah I find the colours too flat (solid) and too strong/bright

---
Side note, I feel simplicity/easy to follow > detail and flourish. Actually, I guess that's another reason full page images might not be a good thing. It tends to make a very good "title page", but then you have little information and have to scroll down. If you look at [Digital Ocean](https://www.digitalocean.com) without scrolling down you see their main point - "deploy on SSD in 50 seconds". If you look at [Nodecraft](https://nodecraft.com) right now you see their christmas special. If you look at [Sponge](https://www.spongepowered.org)... I guess it's cluttered, but actually I still like it (maybe bias?), but there's a lot of information (links, news, code, etc.) and I don't have trouble following it

Especially since not many people know about gamocosm, and I don't think there's really anything like it, the design should be relatively simple and not take away from the messages

---
Maybe here you can give me feedback, what do *you* think about the current front page? Since I made it and stare at it all the time I'm biased xD (myself the first thing is the 3 green buttons are so ugly T__T )

I have a habit of writing a lot xD sorry if it's a lot to read. Don't feel like you have to respond quickly, do this for fun :)

**Comment by Ajusa** [comment]
I also agree with the fact that some of the current design is
outdated/common. I will be adding some code, popping into IRC to show you a
design, as soon as I finish my homework :P
You have a good idea though, and I will try to make it into reality

**Comment by Ajusa** [comment]
Alright, work has started in my github repository! I advise you to look at it and tell me what you think of the style.

**Comment by Raekye** [comment]
Hey, got a last exam tomorrow, so I'll get back to you hopefully in a couple days. Sorry about it! Happy holidays ^^

**Comment by Ajusa** [comment]
Okay! Good luck :D

**Comment by Raekye** [comment]
Hi Ajusa, very sorry for the late response. There were issues I had to deal with over the break but that's no excuse for going silent, my apologies. I know what it's like trying to contact a project maintainer and it can be really frustrating >.<

I've looked at it, I promise (for what it's worth) to give more detailed thoughts this weekend. It looks good, but I'm not fully sold on the full screen hero unit. This is just my opinion, but it seemed popular when all the "web 2.0" stuff started becoming common, but I don't actually know any big sites that still use it. Compared to a solid background (maybe with a smaller picture/design), it takes up a lot of space and makes what text there is harder to focus. But again, maybe it's just me and my eyes focussing problem xD

**Comment by Ajusa** [comment]
Wow, I almost forgot about this XD.
I have some plans on doing a redesign of the backend, which will just be a static site. You will have to hook it up through code, but that shouldn't be too bad.

Also, I too had finals a few weeks ago. They were rough and distracted me from all code.

I'll be working on this. I'll update with a link once I have something more solid for you to check out.

**Comment by Ajusa** [comment]
Now that you are back, I can start working on this again. I spent a few hours today trying out a lot of design, so I would really appreciate it if you could give me some feedback. I basically started over, since my code was really bad and I have learned a lot since I first posted this issue. 
[https://github.com/Ajusa/gamocosm-site](https://github.com/Ajusa/gamocosm-site)
Link to anyone else who wants to help out.

**Comment by binary-koan** [comment]
Hey, I had a go at putting Gamocosm on my own server the other day (because I couldn't wait a few days for the updated Forge versions to be merged ...) but also tried changing the server dashboard around to feel a bit more modern and more like DigitalOcean (which I think is a good thing to aim for). Haven't done much to the CSS side of things so it still looks a bit Bootstrappy, but I'm curious what you think of the layout :)

<img width="936" alt="screen shot 2016-11-10 at 2 20 36 pm" src="https://cloud.githubusercontent.com/assets/1077405/20161273/1fad9368-a752-11e6-99f1-80edcbb82c4c.png">

**Comment by Raekye** [comment]
Oh damn, sorry Ajusa >.< uh I'm really bad at this...

@binary-koan that looks great! If it looks alright with the other pages I'd be happy to work with you to merge it, or if you want to keep working on it I think it looks good!

[Christopher Mundle](https://github.com/cmundle) has also been working on some mock ups, though last I saw he started with the landing/servers pages. If you're both interested I think it'd be good to collaborate! I'll make sure he sees this

Thanks for your contribution!

**Comment by Ajusa** [comment]
It is fine Raekye 
What did you think of my landing page? Also, I am still interested in helping out. I will try and replicate the layout that @binary-koan came up with and try and add more custom css. My goal is to strip out the bootstrap while keeping the responsiveness.

**Comment by Raekye** [comment]
This one right? ajusa.github.io/gamocosm-site/ I think it looks good! A little plain right now but I understand it's a prototype :) I'll try to get cmundle in on this

**Comment by binary-koan** [comment]
Cool, I'll make a PR for the control panel stuff and keep playing around with the rest of the site :)

As usual I did way more than I intended and started changing around the landing page as well (I'm on holiday and don't have anything better to do 😉) Here's what I've done so far, curious to see how it compares to @Ajusa and @cmundle's ideas for it!

Also Ajusa, IMHO it would be easier to configure Bootstrap and add custom CSS where necessary than try to get rid of the framework entirely - it's somewhat configurable (see http://getbootstrap.com/customize/#less-variables) and overriding styles you don't like doesn't add much extra bloat. Might also be a good idea to work in SASS rather than plain CSS since it's already in use for the site and makes for cleaner and more maintainable code.

<img width="883" alt="screen shot 2016-11-12 at 7 20 55 pm" src="https://cloud.githubusercontent.com/assets/1077405/20236244/b4a8bc46-a913-11e6-8663-25b717370ee5.png">

**Comment by Ajusa** [comment]
@binary-koan
I am not against using a framework. I just happen to use my own custom framework that is a combination of a simple grid with Tachyons, a very modular CSS library. I highly recommend you check it out, it has literally changed the way I code.

@Raekye, yeah it's pretty plain. I am planning on adding some more design, and a few images as well. I'll update you once that is up.

**Comment by Raekye** [comment]
Thanks for your contributions! I look forward to your work :)

I can add you guys to the Gamocosm slack (quite quiet xD ) if you wish to be able to chat

I am looking into supporting Linode, as it's now half the price of DO. I've never really pushed Gamocosm in the marketing sense as I'm totally not a marketing person. Also I figured most people would turn away as it looked very "just another open source project" rather than something professional. But after hopefully Linode support and the website redesign we can really try to get some big awareness!

As always, if you guys have any suggestions or feedback would love to hear it. One step at a time, but if you want to help with that too later I could use it xD

**Comment by binary-koan** [comment]
Yeah, any more discussion would probably be easier to follow on Slack ... My commit email is fine :)

I haven't looked at Linode for ages - I'd be interested to see how their server creation/boot times compare to DigitalOcean. Good idea though, and it would be nice to have multiple backends in general!

**Comment by Raekye** [comment]
Sent you an invite, let me know if you don't see it

**Comment by Ajusa** [comment]
My commit email should also be fine!

**Comment by Raekye** [comment]
Added :)

**Comment by Ajusa** [comment]
Uh... Since this is done, I am going to close this issue. New UI looks great!
