### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by Andrewrf** [Gamocosm/Gamocosm#76]
Is Gamocosm still being maintained? It doesnt seem to support new versions of minecraft and everytime I try to connect to my server, the connection is refused. All of my friends are getting the same error.

**Comment by Raekye** [comment]
Regrettably.. as you can probably tell by now, not really :/ It only gets sporadically updated (less and less), and I don't have a habit of checking on it to fix bugs (and Github seems really random on when it decides to send me emails about issues). The latest issue was caused by Digital Ocean dropping support for older versions of Fedora (thanks Bearbin and jbw91)... should be uncommon (I do update the base image from time to time, never had an issue where support was dropped before I updated it), I'll try to be mindful of that now. I *believe* a lot of other bugs have been ironed out over time, but no guarantees :/

Anyways, it really does touch me hearing people still using Gamocosm, I really do appreciate your interest, patience, and use, which is why I want to thank you (and others reading this) for it. Obviously, after these incidents, I don't expect anyone to really want to keep using it, but well, I never intend to fully drop it. It's just... really really slow and poor support haha. I do have a lot of problems IRL, if I can pull myself together.. maintenance would be better

Idk, hopefully that was a clear and honest answer on what to expect? I suppose I should officially open up looking for new project maintainers if I can't do it. Just started winter break for me, hopefully I can do some overhaul over the next 2 weeks.

**Comment by jbw91** [comment]
This is an awesome service @Raekye! I'm thrilled you're giving any support to it at all, so don't worry about that! I think it would be awesome if there were some official project maintainers/contributors, that way you're not constantly spammed by stuff when you're not able to devote time to this. This is such an amazing service, I'd absolutely hate to see it die! Let me know if there's any way I can help out with anything! :)
