### ISSUE TITLE
Domain not working?

### ISSUE THREAD

**Issue by Ajusa** [Gamocosm/Gamocosm#79]
Hey,
I just created a new 1.12 world on the new digital ocean plan (1gb, .7 cents) and the autoshutdown hasn't worked once yet. Is there a bug with the new digital ocean servers?

**Comment by Ajusa** [comment]
I also can't FTP/SSH in anymore -  I get connection errors saying something like `no supported authentication methods available`

**Comment by Ajusa** [comment]
and some of my friends have been complaining that only the direct IP works now, the gamocosm provided url only works after a restart or something.

I have been unable to replicate that issue, but putting it here in case someone else had it.

**Comment by Raekye** [comment]
As for FTP/SSH, I'm not aware of anything that would cause the issue. I'll add wiki pages on how to access your server through DO's control panel to manually enable whatever SSH authentication methods are desired in case it somehow got reset (again, not sure what would have happened though o.O )

As for autoshutdown, the background worker is still going, I'll test this myself tonight

As for the domain names, I'll check if something changed with Cloudflare (the DNS service) and test it too

**Comment by Raekye** [comment]
Wow you are far more timely than me :sweat_smile: I've added this page which documents everything I could think of. https://github.com/Gamocosm/Gamocosm/wiki/Regaining-Server-Access

I thought perhaps the new fedora version disables password authentication for SSH by default... but I checked and that's already edited (to enable password authentication) by Gamocosm. I created a new server and am able to SSH into it via both the IP and gamocosm URL

Were you previously using keys for SSH? For `no supported authentication methods available`, I would check the `~/.ssh` and `authorized_keys` file have the right permissions (700 and 644 respectively should be ok), possibly they got modified by accident and then SSH would be unhappy. I'll be around for a while tonight (and hopefully more from now on... for the billionth time >< )

**Comment by Raekye** [comment]
Autoshutdown seemed to work for my new server. Do you know if you still have the issue?

**Comment by Ajusa** [comment]
I believe I still do. My dash says that the last successful autoshutdown check was 19 days ago.

Is there an easy way of making a new server without having to reinvite all my friends?

**Comment by Raekye** [comment]
Unfortunately no easy way of migrating all your friends, if you want you can PM me (irc or gitter chat or reddit - see the README I added it) the server UUIDs and I can do it in the database. I realized, just in case, if you set it up yourself, did you set `enable-query=true` in `server.properties`? For autoshutdown. I thought I documented it better, but looking through the wiki apparently not (but see https://github.com/Gamocosm/gamocosm-minecraft-flavours/blob/master/vanilla.sh as reference)

**Comment by Ajusa** [comment]
I think that might be it. I am checking now...

**Comment by Ajusa** [comment]
Yep, enabled and it says it had a successful check! I am still having the DNS issue, I will probably make a new server and then PM you to move everything over. Thank you so much for your support!

**Comment by Raekye** [comment]
Great! Actually if you just want to PM me your current server I can take a look first to see if Ican see what's up with the domain (or transferring works too)

**Comment by Ajusa** [comment]
Just PM'd

**Comment by Raekye** [comment]
Indeed there seems to have been an error with updating existing domain names, which is why the quick test with a new server didn't show it. Pretty sure I know how to fix it, gonna do it right now, though it seems Cloudflare also has a new API I should look into updating it for the long term. In the mean time I manually updated your DNS record (since DO tries to re-use IPs). Thanks for your patience and help finding these bugs!

**Comment by Raekye** [comment]
Oops that doesn't fix it :sweat_smile: The problem was with the v1 Cloudflare API:
- updating a DNS record requires its internal Cloudflare ID
- the only API to get the ID is to list all records
- it seems that endpoint only returns 180 records

So Gamocosm didn't find your DNS record in the 180, tried to add it, but got an "already exists" error (and silently fails). In hindsight, it may have been been better to save the ID when creating a DNS record, but at the time it didn't seem like a big deal and saving additional data which "should" have been fetchable seemed like room for error

Also, it seems Cloudflare took their API v1 docs down, so I can't check for workarounds. I'll probably just focus on updating to v4, which seems much more flexible (e.g. don't need ID to update record). For now, unfortunately you will need to use the IP (if it changes from the original domain)

**Comment by Ajusa** [comment]
Well, it appears that my domain works now, so thanks!

Yeah, this seems like a massive pain, thanks so much for being willing to update this project.
