### ISSUE TITLE
Detect when enable-query=false is enabled on Autoshutdown

### ISSUE THREAD

**Issue by Simon-Laux** [Gamocosm/Gamocosm#95]
And correct it to true or at least tell the server admin in the error email

**Comment by Raekye** [comment]
This is, while technically very possible, a little troublesome, as there would be a few moving parts for a very specific thing. This would be low priority on the list of new features, but I'll leave it open and hopefully I'll get around to it. As things are, Gamocosm sets `enable-query=true` by default, so this case shouldn't occur unless the server admin specifically disables it. I suppose this could also happen if the user is transferring an existing server

**Comment by hazi98** [comment]
Just a quick observation but for some reason I got a PaperMC 1.14.4 server, and this option was set to false as default. I didn't know this option was needed in order to enable Autoshutdown, although I didn't set it to false either.

**Comment by Raekye** [comment]
I've added messages in the email for the autoshutdown failure, as well as the autoshutdown panel indicating the need for `enable-query=true`. Hopefully it's more clear now

As for your PaperMC server, did you set it up yourself (e.g. via SSH), or did you use Gamocosm's preset option? Because I checked the preset option _should_ set `enable-query=true`. I haven't tested it myself though

**Comment by hazi98** [comment]
I set it up myself, I downloaded the server from the website and copied the jar via SFTP

**Comment by Raekye** [comment]
I see, thanks for confirming. With the new messages hopefully it's more clear to people in the future now. Going to close this issue (but feel free to continue the discussion if I missed something)
