### ISSUE TITLE
Extra Feature: More Server host choices, like vultr, hetzner etc

### ISSUE THREAD

**Issue by xlnd47** [Gamocosm/Gamocosm#97]
Would be nice to run my server on Hetzner

**Comment by Raekye** [comment]
Hello, sorry for the late response. Unfortunately, I don't have plans to add more server host choices. It's been requested since the beginning, but there are a lot of things that can go wrong in the server starting/stopping process, and it's already a bit of a hassle to manage all the possible errors from Digital Ocean (I'm not even sure I'm doing it that well). So adding more host choices just makes it much less manageable, which I'm not doing a good job of managing Gamocosm already. Sorry :( If you have any further questions or suggestions I would be open to listen
